name: Functionality Test (Dispatch)

on:
  workflow_dispatch:
    inputs:
      amf_patch:
        description: 'NF patch'
        required: false
        type: string
      ausf_patch:
        description: 'NF patch'
        required: false
        type: string
      n3iwf_patch:
        description: 'NF patch'
        required: false
        type: string
      nrf_patch:
        description: 'NF patch'
        required: false
        type: string
      nssf_patch:
        description: 'NF patch'
        required: false
        type: string
      pcf_patch:
        description: 'NF patch'
        required: false
        type: string
      smf_patch:
        description: 'NF patch'
        required: false
        type: string
      udm_patch:
        description: 'NF patch'
        required: false
        type: string
      udr_patch:
        description: 'NF patch'
        required: false
        type: string
      upf_patch:
        description: 'NF patch'
        required: false
        type: string
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.3

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: 4.4

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install netcat psmisc iproute2 git gcc g++ cmake autoconf libtool pkg-config libmnl-dev libyaml-dev

    - name: Build
      run: |
        git submodule init
        git submodule sync
        git submodule update
        ./patch.sh
        make
      env:
        AMF_PATCH: ${{ inputs.amf_patch }}
        SMF_PATCH: ${{ inputs.smf_patch }}
        UPF_PATCH: ${{ inputs.upf_patch }}
        UDR_PATCH: ${{ inputs.udr_patch }}
        UDM_PATCH: ${{ inputs.udm_patch }}
        NRF_PATCH: ${{ inputs.nrf_patch }}
        NSSF_PATCH: ${{ inputs.nssf_patch }}
        AUSF_PATCH: ${{ inputs.ausf_patch }}
        N3IWF_PATCH: ${{ inputs.n3iwf_patch }}
        PCF_PATCH: ${{ inputs.pcf_patch }}

    - name: Basic Test
      run: |
        ls bin/ -al
        ./test_ci.sh TestRegistration
        sleep 1
        ./test_ci.sh TestGUTIRegistration
        sleep 1
        ./test_ci.sh TestServiceRequest
        sleep 1
        ./test_ci.sh TestXnHandover
        sleep 1
        ./test_ci.sh TestDeregistration
        sleep 1
        ./test_ci.sh TestPDUSessionReleaseRequest
        sleep 1
        ./test_ci.sh TestPaging
        sleep 1
        ./test_ci.sh TestN2Handover
        sleep 1
        ./test_ci.sh TestReSynchronization
    - name: ULCL Test
      run: ./test_ci_ulcl.sh TestRequestTwoPDUSessions
    - name: remove uncommitted changes
      run: ./patch.sh
